project_id = "wrklxbeptvtiqxxjatrx"

[functions.bpjs-vclaim]
verify_jwt = false

[functions.bpjs-icare]
verify_jwt = false

[functions.satusehat]
verify_jwt = false

[functions.bpjs-antrean]
verify_jwt = false

[functions.bpjs-eclaim]
verify_jwt = false

[functions.eklaim-idrg]
verify_jwt = false

[functions.pacs-bridge]
verify_jwt = false
