version: '3.8'

services:
  app:
    image: yourusername/yourapp:latest
    ports:
      - '80:80'
    environment:
      - ENV_VAR_NAME=value

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
