# This workflow is currently disabled for pushes to main branch.
# push:
#   branches:
#     - main

name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo Building...